/*
 * Copyright (c) 2025-2026 Datalayer, Inc.
 * Distributed under the terms of the Modified BSD License.
 */

/**
 * Team Specifications.
 *
 * THIS FILE IS AUTO-GENERATED from YAML team specifications.
 * DO NOT EDIT MANUALLY - run 'make specs' to regenerate.
 */

import type { TeamSpec } from '../../types';

// ============================================================================
// Team Definitions
// ============================================================================

export const ANALYZE_CAMPAIGN_PERFORMANCE_TEAM_SPEC_0_0_1: TeamSpec = {
  id: 'analyze-campaign-performance',
  version: '0.0.1',
  name: 'Analyze Campaign Performance',
  description: `A multi-agent team that unifies marketing data from Google Ads, Meta, TikTok, LinkedIn, GA4, CRM, and email platforms. Normalises metrics into a unified view, detects performance anomalies in real time, and generates budget reallocation recommendations to maximise ROAS.`,
  tags: [
    'marketing',
    'media',
    'campaigns',
    'analytics',
    'advertising',
    'social-media',
  ],
  enabled: true,
  icon: 'megaphone',
  emoji: '📢',
  color: '#8250df',
  agentSpecId: 'analyze-campaign-performance:0.0.1',
  orchestrationProtocol: 'datalayer',
  executionMode: 'sequential',
  supervisor: {
    name: 'Campaign Analytics Orchestrator Agent',
    model: 'openai-gpt-4-1',
  },
  routingInstructions: `Start with Platform Connector to pull data from all ad platforms, then Metrics Normaliser for unified KPIs, then Anomaly Detector for real-time performance monitoring, then Budget Optimiser for reallocation recommendations. Escalate CPA spikes above 50% immediately.`,
  validation: { timeout: '300s', retryOnFailure: true, maxRetries: 2 },
  agents: [
    {
      id: 'cp-1',
      name: 'Platform Connector Agent',
      role: 'Primary · Initiator',
      goal: `Pull campaign data from Google Ads, Meta, TikTok, LinkedIn, GA4, and email platforms`,
      model: 'openai-gpt-4-1',
      mcpServer: 'Ad Platforms MCP',
      tools: [
        'Google Ads Connector',
        'Meta Ads Connector',
        'TikTok Ads Connector',
        'LinkedIn Ads Connector',
        'GA4 Connector',
      ],
      trigger: 'Schedule: Every 4 hours',
      approval: 'auto',
    },
    {
      id: 'cp-2',
      name: 'Metrics Normaliser Agent',
      role: 'Secondary',
      goal: `Normalise CPA, ROAS, CTR, and attribution across all platforms into unified view`,
      model: 'openai-gpt-4-1',
      mcpServer: 'Analytics MCP',
      tools: [
        'Metric Unifier',
        'Currency Converter',
        'Attribution Mapper',
        'Naming Convention Resolver',
      ],
      trigger: 'On completion of Platform Connector Agent',
      approval: 'auto',
    },
    {
      id: 'cp-3',
      name: 'Anomaly Detector Agent',
      role: 'Secondary',
      goal: `Monitor all KPIs for CTR drops, CPA spikes, and budget pacing issues`,
      model: 'anthropic-claude-sonnet-4',
      mcpServer: 'Monitoring MCP',
      tools: [
        'Anomaly Scanner',
        'Budget Pacer',
        'Alert Generator',
        'Campaign Pauser',
      ],
      trigger: 'On completion of Metrics Normaliser Agent',
      approval: 'manual',
    },
    {
      id: 'cp-4',
      name: 'Budget Optimiser Agent',
      role: 'Final',
      goal: `Generate budget reallocation recommendations to maximise ROAS across channels`,
      model: 'openai-gpt-4-1',
      mcpServer: 'Optimisation MCP',
      tools: [
        'ROAS Calculator',
        'Budget Allocator',
        'Scenario Modeller',
        'Report Generator',
      ],
      trigger: 'On completion of Anomaly Detector Agent',
      approval: 'manual',
    },
  ],
  reactionRules: [
    {
      id: 'rr-camp-1',
      trigger: 'budget_threshold_exceeded',
      action: 'pause_and_notify',
      auto: true,
      maxRetries: 1,
      escalateAfterRetries: 1,
      priority: 'high',
    },
    {
      id: 'rr-camp-2',
      trigger: 'data_quality_low',
      action: 'retry_collection',
      auto: true,
      maxRetries: 3,
      escalateAfterRetries: 3,
      priority: 'medium',
    },
  ],
  healthMonitoring: {
    heartbeatInterval: '30s',
    staleThreshold: '120s',
    unresponsiveThreshold: '300s',
    stuckThreshold: '600s',
    maxRestartAttempts: 3,
  },
  notifications: {
    on_start: true,
    on_completion: true,
    on_failure: true,
    on_escalation: true,
  },
  output: {
    formats: ['pdf', 'csv', 'json'],
    template: 'Campaign Performance Report',
    storage: 's3://reports/campaign-analytics/',
  },
};

export const ANALYZE_SUPPORT_TICKETS_TEAM_SPEC_0_0_1: TeamSpec = {
  id: 'analyze-support-tickets',
  version: '0.0.1',
  name: 'Analyze Support Tickets',
  description: `A multi-agent team that triages incoming support tickets, categorizes by urgency and topic, identifies recurring patterns, and generates resolution recommendations with escalation paths.`,
  tags: ['analytics', 'data', 'support', 'tickets'],
  enabled: true,
  icon: 'issue-opened',
  emoji: '🎫',
  color: '#bf8700',
  agentSpecId: 'analyze-support-tickets:0.0.1',
  orchestrationProtocol: 'datalayer',
  executionMode: 'sequential',
  supervisor: { name: 'Support Orchestrator Agent', model: 'openai-gpt-4-1' },
  routingInstructions: `Route new tickets to the Triage Agent first, then to the Categorizer, then to the Pattern Analyzer. Escalate P1/critical tickets immediately to human support leads.`,
  validation: { timeout: '180s', retryOnFailure: true, maxRetries: 2 },
  agents: [
    {
      id: 'st-1',
      name: 'Triage Agent',
      role: 'Primary · Initiator',
      goal: `Ingest new support tickets and assess urgency level (P1-P4)`,
      model: 'openai-gpt-4-1',
      mcpServer: 'Helpdesk MCP',
      tools: ['Ticket Reader', 'Priority Classifier'],
      trigger: 'Event: new ticket received',
      approval: 'auto',
    },
    {
      id: 'st-2',
      name: 'Categorizer Agent',
      role: 'Secondary',
      goal: `Categorize tickets by topic, product area, and sentiment`,
      model: 'openai-gpt-4-1',
      mcpServer: 'NLP Pipeline MCP',
      tools: ['Topic Classifier', 'Sentiment Analyzer', 'Product Tagger'],
      trigger: 'On completion of Triage Agent',
      approval: 'auto',
    },
    {
      id: 'st-3',
      name: 'Pattern Analyzer Agent',
      role: 'Final',
      goal: `Identify recurring issues and generate resolution recommendations`,
      model: 'anthropic-claude-sonnet-4',
      mcpServer: 'Analytics MCP',
      tools: [
        'Pattern Detector',
        'Knowledge Base Search',
        'Resolution Generator',
      ],
      trigger: 'On completion of Categorizer Agent',
      approval: 'manual',
    },
  ],
  reactionRules: [
    {
      id: 'rr-supp-1',
      trigger: 'ticket_surge_detected',
      action: 'escalate_to_supervisor',
      auto: true,
      maxRetries: 2,
      escalateAfterRetries: 2,
      priority: 'high',
    },
    {
      id: 'rr-supp-2',
      trigger: 'classification_confidence_low',
      action: 'request_human_review',
      auto: false,
      maxRetries: 1,
      escalateAfterRetries: 1,
      priority: 'medium',
    },
  ],
  healthMonitoring: {
    heartbeatInterval: '15s',
    staleThreshold: '60s',
    unresponsiveThreshold: '180s',
    stuckThreshold: '300s',
    maxRestartAttempts: 3,
  },
  notifications: {
    on_start: false,
    on_completion: true,
    on_failure: true,
    on_escalation: true,
  },
  output: {
    formats: ['pdf', 'json'],
    template: 'Support Ticket Analysis',
    storage: 's3://reports/support-analytics/',
  },
};

export const AUDIT_INVENTORY_LEVELS_TEAM_SPEC_0_0_1: TeamSpec = {
  id: 'audit-inventory-levels',
  version: '0.0.1',
  name: 'Audit Inventory Levels',
  description: `A multi-agent team that monitors inventory levels across warehouses, detects discrepancies between physical and system counts, forecasts demand by SKU, and generates automated reorder recommendations.`,
  tags: ['finance', 'automation', 'inventory', 'supply-chain'],
  enabled: true,
  icon: 'package',
  emoji: '📦',
  color: '#0969da',
  agentSpecId: 'audit-inventory-levels:0.0.1',
  orchestrationProtocol: 'datalayer',
  executionMode: 'sequential',
  supervisor: { name: 'Inventory Orchestrator Agent', model: 'openai-gpt-4-1' },
  routingInstructions: `Start with the Scanner to pull current levels, then Auditor to check discrepancies, then Forecaster for demand predictions, then Planner for reorder recommendations, then Reporter for the final audit report. Escalate critical shortages immediately.`,
  validation: { timeout: '600s', retryOnFailure: true, maxRetries: 3 },
  agents: [
    {
      id: 'inv-1',
      name: 'Inventory Scanner Agent',
      role: 'Primary · Initiator',
      goal: `Pull current inventory levels from all warehouse management systems`,
      model: 'openai-gpt-4-1',
      mcpServer: 'Warehouse MCP',
      tools: ['WMS Connector', 'Barcode Scanner API'],
      trigger: 'Schedule: Every 6 hours',
      approval: 'auto',
    },
    {
      id: 'inv-2',
      name: 'Discrepancy Auditor Agent',
      role: 'Secondary',
      goal: `Compare system counts vs physical counts and flag discrepancies`,
      model: 'openai-gpt-4-1',
      mcpServer: 'Audit MCP',
      tools: ['Count Comparator', 'Discrepancy Logger', 'Shrinkage Calculator'],
      trigger: 'On completion of Inventory Scanner',
      approval: 'auto',
    },
    {
      id: 'inv-3',
      name: 'Demand Forecaster Agent',
      role: 'Secondary',
      goal: `Forecast demand by SKU using historical sales and seasonal patterns`,
      model: 'anthropic-claude-sonnet-4',
      mcpServer: 'Analytics MCP',
      tools: [
        'Time Series Model',
        'Seasonal Analyzer',
        'External Signals Fetcher',
      ],
      trigger: 'On completion of Discrepancy Auditor',
      approval: 'auto',
    },
    {
      id: 'inv-4',
      name: 'Reorder Planner Agent',
      role: 'Secondary',
      goal: `Calculate optimal reorder points and generate purchase order recommendations`,
      model: 'openai-gpt-4-1',
      mcpServer: 'Procurement MCP',
      tools: ['EOQ Calculator', 'Supplier Catalog', 'PO Generator'],
      trigger: 'On completion of Demand Forecaster',
      approval: 'manual',
    },
    {
      id: 'inv-5',
      name: 'Audit Report Agent',
      role: 'Final',
      goal: `Compile inventory audit report with discrepancies, forecasts, and reorder plan`,
      model: 'openai-gpt-4-1',
      mcpServer: 'Document Generation MCP',
      tools: ['PDF Generator', 'Chart Builder', 'Email Sender'],
      trigger: 'On completion of Reorder Planner',
      approval: 'auto',
    },
  ],
  reactionRules: [
    {
      id: 'rr-inv-1',
      trigger: 'stockout_risk_detected',
      action: 'escalate_to_supervisor',
      auto: true,
      maxRetries: 1,
      escalateAfterRetries: 1,
      priority: 'high',
    },
    {
      id: 'rr-inv-2',
      trigger: 'discrepancy_threshold_exceeded',
      action: 'flag_for_manual_audit',
      auto: false,
      maxRetries: 2,
      escalateAfterRetries: 2,
      priority: 'high',
    },
  ],
  healthMonitoring: {
    heartbeatInterval: '30s',
    staleThreshold: '120s',
    unresponsiveThreshold: '300s',
    stuckThreshold: '600s',
    maxRestartAttempts: 3,
  },
  notifications: {
    on_start: true,
    on_completion: true,
    on_failure: true,
    on_escalation: true,
  },
  output: {
    formats: ['pdf', 'xlsx', 'csv'],
    template: 'Inventory Audit Report',
    storage: 's3://reports/inventory-audits/',
  },
};

export const AUTOMATE_REGULATORY_REPORTING_TEAM_SPEC_0_0_1: TeamSpec = {
  id: 'automate-regulatory-reporting',
  version: '0.0.1',
  name: 'Automate Regulatory Reporting',
  description: `A multi-agent team that automates end-to-end regulatory reporting for financial institutions. Ingests data from trading systems, risk engines, and accounting platforms, reconciles positions, computes risk metrics, validates against regulatory rules (Basel III/IV, MiFID II, SOX), and generates submission-ready compliance reports with full audit trails.`,
  tags: ['finance', 'compliance', 'regulatory', 'risk', 'banking', 'audit'],
  enabled: true,
  icon: 'shield-check',
  emoji: '🏦',
  color: '#0969da',
  agentSpecId: 'automate-regulatory-reporting:0.0.1',
  orchestrationProtocol: 'datalayer',
  executionMode: 'sequential',
  supervisor: {
    name: 'Compliance Orchestrator Agent',
    model: 'openai-gpt-4-1',
  },
  routingInstructions: `Start with Data Ingestion to pull positions and transactions, then Risk Calculator for metric computation, then Reconciliation Agent to cross-check figures, then Validation Agent for regulatory rule checks, then Report Generator for submission-ready output. Escalate any reconciliation breaks above $10K immediately to the compliance team.`,
  validation: { timeout: '900s', retryOnFailure: true, maxRetries: 2 },
  agents: [
    {
      id: 'reg-1',
      name: 'Data Ingestion Agent',
      role: 'Primary · Initiator',
      goal: `Extract positions, transactions, and P&L from trading and accounting systems`,
      model: 'openai-gpt-4-1',
      mcpServer: 'Trading Systems MCP',
      tools: ['Position Reader', 'Transaction Fetcher', 'P&L Extractor'],
      trigger: 'Schedule: Monthly on the 3rd business day',
      approval: 'auto',
    },
    {
      id: 'reg-2',
      name: 'Risk Calculator Agent',
      role: 'Secondary',
      goal: `Compute Basel III/IV risk-weighted assets, capital ratios, and VaR metrics`,
      model: 'anthropic-claude-sonnet-4',
      mcpServer: 'Risk Engine MCP',
      tools: [
        'RWA Calculator',
        'VaR Engine',
        'Capital Ratio Computer',
        'Stress Test Runner',
      ],
      trigger: 'On completion of Data Ingestion Agent',
      approval: 'auto',
    },
    {
      id: 'reg-3',
      name: 'Reconciliation Agent',
      role: 'Secondary',
      goal: `Cross-check computed figures against source systems and flag discrepancies`,
      model: 'openai-gpt-4-1',
      mcpServer: 'Reconciliation MCP',
      tools: ['Position Reconciler', 'Break Detector', 'Audit Logger'],
      trigger: 'On completion of Risk Calculator Agent',
      approval: 'auto',
    },
    {
      id: 'reg-4',
      name: 'Validation Agent',
      role: 'Secondary',
      goal: `Validate all metrics against Basel III/IV, MiFID II, and SOX regulatory rules`,
      model: 'openai-gpt-4-1',
      mcpServer: 'Compliance Rules MCP',
      tools: [
        'Basel Rule Validator',
        'MiFID II Checker',
        'SOX Control Verifier',
      ],
      trigger: 'On completion of Reconciliation Agent',
      approval: 'manual',
    },
    {
      id: 'reg-5',
      name: 'Report Generator Agent',
      role: 'Final',
      goal: `Generate submission-ready regulatory reports with full data lineage and audit trail`,
      model: 'openai-gpt-4-1',
      mcpServer: 'Document Generation MCP',
      tools: ['PDF Generator', 'XBRL Formatter', 'Email Sender'],
      trigger: 'On completion of Validation Agent',
      approval: 'auto',
    },
  ],
  reactionRules: [
    {
      id: 'rr-reg-1',
      trigger: 'compliance_violation_detected',
      action: 'halt_and_escalate',
      auto: true,
      maxRetries: 0,
      escalateAfterRetries: 0,
      priority: 'critical',
    },
    {
      id: 'rr-reg-2',
      trigger: 'data_validation_failure',
      action: 'retry_with_fallback',
      auto: true,
      maxRetries: 3,
      escalateAfterRetries: 3,
      priority: 'high',
    },
  ],
  healthMonitoring: {
    heartbeatInterval: '15s',
    staleThreshold: '60s',
    unresponsiveThreshold: '120s',
    stuckThreshold: '300s',
    maxRestartAttempts: 2,
  },
  notifications: {
    on_start: true,
    on_completion: true,
    on_failure: true,
    on_escalation: true,
  },
  output: {
    formats: ['pdf', 'xbrl', 'json'],
    template: 'Regulatory Submission Report',
    storage: 's3://reports/regulatory-submissions/',
  },
};

export const COMPREHENSIVE_SALES_ANALYTICS_TEAM_SPEC_0_0_1: TeamSpec = {
  id: 'comprehensive-sales-analytics',
  version: '0.0.1',
  name: 'Comprehensive Sales Analytics',
  description: `A multi-agent team that replaces a single KPI monitor with four specialized agents: a Data Collector that pulls real-time CRM metrics, an Anomaly Detector that flags statistical outliers, a Trend Analyzer that identifies patterns and forecasts, and a Report Generator that compiles executive dashboards and sends alerts. Together they deliver deeper insights, faster detection, and richer reporting than any single agent could.`,
  tags: ['sales', 'analytics', 'kpi', 'monitoring', 'horizontal'],
  enabled: true,
  icon: 'graph',
  emoji: '📈',
  color: '#1a7f37',
  agentSpecId: 'comprehensive-sales-analytics:0.0.1',
  orchestrationProtocol: 'datalayer',
  executionMode: 'sequential',
  supervisor: {
    name: 'Sales Analytics Supervisor',
    model: 'anthropic-claude-opus-4',
  },
  routingInstructions: `Route data collection to KPI Collector first, then pass raw metrics to Anomaly Detector and Trend Analyzer in parallel, then aggregate all outputs into the Report Generator. Escalate if anomalies exceed the critical threshold (>25% deviation from target).`,
  validation: { timeout: '300s', retryOnFailure: true, maxRetries: 3 },
  agents: [
    {
      id: 'sa-1',
      name: 'KPI Data Collector',
      role: 'Primary · Initiator',
      goal: `Pull real-time sales metrics from CRM, ERP, and marketing platforms. Normalize data into a unified schema with timestamps, dimensions (region, product line, rep), and measures (revenue, pipeline, conversion).`,
      model: 'openai-gpt-4-1',
      mcpServer: 'CRM Data Server',
      tools: ['get_sales_data', 'get_customer_list', 'API Connector'],
      trigger: 'Schedule: Daily at 7:30 AM',
      approval: 'auto',
    },
    {
      id: 'sa-2',
      name: 'Anomaly Detector',
      role: 'Secondary',
      goal: `Apply statistical anomaly detection (Z-score, IQR, moving average) to the collected KPIs. Flag any metric deviating more than 10% from its rolling 30-day average. Classify anomalies as info, warning, or critical.`,
      model: 'anthropic-claude-sonnet-4',
      mcpServer: 'Analytics Server',
      tools: ['run_analysis', 'Statistical Analysis', 'ML Predictor'],
      trigger: 'On completion of KPI Data Collector',
      approval: 'auto',
    },
    {
      id: 'sa-3',
      name: 'Trend Analyzer',
      role: 'Secondary',
      goal: `Identify week-over-week, month-over-month, and quarter-over-quarter trends. Generate 30-day forecasts for each KPI using time-series models. Highlight the top 3 improving and top 3 declining metrics.`,
      model: 'anthropic-claude-sonnet-4',
      mcpServer: 'Analytics Server',
      tools: ['run_analysis', 'generate_charts', 'Forecaster'],
      trigger: 'On completion of KPI Data Collector',
      approval: 'auto',
    },
    {
      id: 'sa-4',
      name: 'Executive Report Generator',
      role: 'Final',
      goal: `Compile all insights — raw KPIs, anomalies, trends, and forecasts — into a polished executive dashboard with charts, tables, and narrative commentary. Send the report via Slack and email. Highlight critical anomalies with a red-flag summary at the top.`,
      model: 'openai-gpt-4-1',
      mcpServer: 'Document Generation MCP',
      tools: [
        'PDF Generator',
        'Chart Builder',
        'Email Sender',
        'Slack Notifier',
      ],
      trigger: 'On completion of Anomaly Detector & Trend Analyzer',
      approval: 'manual',
    },
  ],
  reactionRules: [
    {
      id: 'rr-sales-1',
      trigger: 'anomaly_critical',
      action: 'escalate_to_supervisor',
      auto: true,
      maxRetries: 2,
      escalateAfterRetries: 2,
      priority: 'high',
    },
    {
      id: 'rr-sales-2',
      trigger: 'data_stale',
      action: 'retry_collection',
      auto: true,
      maxRetries: 3,
      escalateAfterRetries: 3,
      priority: 'medium',
    },
  ],
  healthMonitoring: {
    heartbeatInterval: '30s',
    staleThreshold: '120s',
    unresponsiveThreshold: '300s',
    stuckThreshold: '600s',
    maxRestartAttempts: 3,
  },
  notifications: {
    on_start: true,
    on_completion: true,
    on_failure: true,
    on_escalation: true,
  },
  output: {
    formats: ['pdf', 'xlsx', 'json'],
    template: 'Executive Sales Dashboard',
    storage: 's3://reports/sales-analytics/',
  },
};

export const OPTIMIZE_GRID_OPERATIONS_TEAM_SPEC_0_0_1: TeamSpec = {
  id: 'optimize-grid-operations',
  version: '0.0.1',
  name: 'Optimize Grid Operations',
  description: `A multi-agent team that processes millions of IoT sensor data points from smart meters, substations, and renewable generation assets. Predicts equipment failures 2–4 weeks in advance, optimises load balancing across the grid, and reduces unplanned downtime by 50%.`,
  tags: [
    'energy',
    'utilities',
    'smart-grid',
    'iot',
    'predictive-maintenance',
    'sustainability',
  ],
  enabled: true,
  icon: 'zap',
  emoji: '⚡',
  color: '#1a7f37',
  agentSpecId: 'optimize-grid-operations:0.0.1',
  orchestrationProtocol: 'datalayer',
  executionMode: 'sequential',
  supervisor: {
    name: 'Grid Operations Orchestrator Agent',
    model: 'openai-gpt-4-1',
  },
  routingInstructions: `Start with Sensor Ingestion to process real-time telemetry, then Anomaly Detector for pattern identification, then Failure Predictor for maintenance forecasting, then Grid Balancer for load optimisation. Escalate critical failure predictions (< 48h) immediately to operations dispatch.`,
  validation: { timeout: '600s', retryOnFailure: true, maxRetries: 3 },
  agents: [
    {
      id: 'grid-1',
      name: 'Sensor Ingestion Agent',
      role: 'Primary · Initiator',
      goal: `Ingest and process real-time telemetry from SCADA, smart meters, and IoT gateways`,
      model: 'openai-gpt-4-1',
      mcpServer: 'SCADA MCP',
      tools: [
        'SCADA Connector',
        'Smart Meter Reader',
        'IoT Gateway Adapter',
        'Time Series Processor',
      ],
      trigger: 'Schedule: Every 5 minutes',
      approval: 'auto',
    },
    {
      id: 'grid-2',
      name: 'Anomaly Detector Agent',
      role: 'Secondary',
      goal: `Detect vibration, temperature, and voltage anomalies across all grid assets`,
      model: 'openai-gpt-4-1',
      mcpServer: 'Monitoring MCP',
      tools: [
        'Vibration Analyzer',
        'Temperature Anomaly Detector',
        'Voltage Pattern Scanner',
        'Historical Comparator',
      ],
      trigger: 'On completion of Sensor Ingestion Agent',
      approval: 'auto',
    },
    {
      id: 'grid-3',
      name: 'Failure Predictor Agent',
      role: 'Secondary',
      goal: `Predict equipment failures 2–4 weeks in advance using anomaly patterns and failure history`,
      model: 'anthropic-claude-sonnet-4',
      mcpServer: 'Predictive Analytics MCP',
      tools: [
        'Failure Correlation Engine',
        'Risk Scorer',
        'Maintenance Scheduler',
        'Work Order Generator',
      ],
      trigger: 'On completion of Anomaly Detector Agent',
      approval: 'manual',
    },
    {
      id: 'grid-4',
      name: 'Grid Balancer Agent',
      role: 'Final',
      goal: `Optimise real-time load balancing across renewable and conventional generation sources`,
      model: 'openai-gpt-4-1',
      mcpServer: 'Grid Control MCP',
      tools: [
        'Load Forecaster',
        'Renewable Integration Model',
        'Dispatch Optimiser',
        'Grid Stability Checker',
      ],
      trigger: 'On completion of Failure Predictor Agent',
      approval: 'auto',
    },
  ],
  reactionRules: [
    {
      id: 'rr-grid-1',
      trigger: 'grid_instability_detected',
      action: 'emergency_rebalance',
      auto: true,
      maxRetries: 1,
      escalateAfterRetries: 1,
      priority: 'critical',
    },
    {
      id: 'rr-grid-2',
      trigger: 'forecast_deviation_high',
      action: 'recalibrate_model',
      auto: true,
      maxRetries: 2,
      escalateAfterRetries: 2,
      priority: 'medium',
    },
  ],
  healthMonitoring: {
    heartbeatInterval: '10s',
    staleThreshold: '30s',
    unresponsiveThreshold: '60s',
    stuckThreshold: '120s',
    maxRestartAttempts: 5,
  },
  notifications: {
    on_start: true,
    on_completion: true,
    on_failure: true,
    on_escalation: true,
  },
  output: {
    formats: ['json', 'csv', 'pdf'],
    template: 'Grid Operations Dashboard',
    storage: 's3://reports/grid-operations/',
  },
};

export const PROCESS_CITIZEN_REQUESTS_TEAM_SPEC_0_0_1: TeamSpec = {
  id: 'process-citizen-requests',
  version: '0.0.1',
  name: 'Process Citizen Requests',
  description: `A multi-agent team that automates citizen request processing for government agencies. Classifies and triages permits, FOIA requests, and benefit claims from multiple channels. Models policy impacts across population datasets and ensures every automated decision is explainable, auditable, and compliant with transparency mandates.`,
  tags: [
    'government',
    'public-sector',
    'civic',
    'policy',
    'compliance',
    'transparency',
  ],
  enabled: true,
  icon: 'organization',
  emoji: '🏛️',
  color: '#0550ae',
  agentSpecId: 'process-citizen-requests:0.0.1',
  orchestrationProtocol: 'datalayer',
  executionMode: 'sequential',
  supervisor: {
    name: 'Citizen Services Orchestrator Agent',
    model: 'openai-gpt-4-1',
  },
  routingInstructions: `Route incoming citizen requests to the Intake Agent for classification and triage, then to the Case Processor for handling and routing, then to the Policy Analyst for impact assessment on relevant items, then to the Transparency Agent for audit trail and public documentation. Escalate urgent citizen safety issues immediately to supervisors.`,
  validation: { timeout: '300s', retryOnFailure: true, maxRetries: 2 },
  agents: [
    {
      id: 'cit-1',
      name: 'Intake & Classification Agent',
      role: 'Primary · Initiator',
      goal: `Classify, triage, and route citizen submissions from web portals, email, and documents`,
      model: 'openai-gpt-4-1',
      mcpServer: 'Citizen Portal MCP',
      tools: [
        'Request Classifier',
        'Urgency Assessor',
        'Jurisdiction Router',
        'OCR Scanner',
      ],
      trigger: 'Event: new citizen request received',
      approval: 'auto',
    },
    {
      id: 'cit-2',
      name: 'Case Processor Agent',
      role: 'Secondary',
      goal: `Process and route requests to appropriate departments with required documentation`,
      model: 'openai-gpt-4-1',
      mcpServer: 'Case Management MCP',
      tools: [
        'Case Creator',
        'Document Assembler',
        'Department Router',
        'Status Tracker',
      ],
      trigger: 'On completion of Intake Agent',
      approval: 'auto',
    },
    {
      id: 'cit-3',
      name: 'Policy Impact Analyst Agent',
      role: 'Secondary',
      goal: `Model policy outcomes across population datasets with scenario simulation`,
      model: 'anthropic-claude-sonnet-4',
      mcpServer: 'Policy Analytics MCP',
      tools: [
        'Monte Carlo Simulator',
        'Demographic Analyzer',
        'Budget Impact Model',
        'Scenario Comparator',
      ],
      trigger: 'On completion of Case Processor Agent',
      approval: 'manual',
    },
    {
      id: 'cit-4',
      name: 'Transparency & Audit Agent',
      role: 'Final',
      goal: `Generate explainable decision documentation with full audit trail for public record`,
      model: 'openai-gpt-4-1',
      mcpServer: 'Compliance MCP',
      tools: [
        'Decision Explainer',
        'Audit Trail Builder',
        'FOIA Compliance Checker',
        'Public Record Generator',
      ],
      trigger: 'On completion of Policy Impact Analyst Agent',
      approval: 'auto',
    },
  ],
  reactionRules: [
    {
      id: 'rr-cit-1',
      trigger: 'priority_request_detected',
      action: 'fast_track_processing',
      auto: true,
      maxRetries: 2,
      escalateAfterRetries: 2,
      priority: 'high',
    },
    {
      id: 'rr-cit-2',
      trigger: 'policy_ambiguity_detected',
      action: 'request_human_review',
      auto: false,
      maxRetries: 1,
      escalateAfterRetries: 1,
      priority: 'medium',
    },
  ],
  healthMonitoring: {
    heartbeatInterval: '30s',
    staleThreshold: '120s',
    unresponsiveThreshold: '300s',
    stuckThreshold: '600s',
    maxRestartAttempts: 3,
  },
  notifications: {
    on_start: false,
    on_completion: true,
    on_failure: true,
    on_escalation: true,
  },
  output: {
    formats: ['pdf', 'json'],
    template: 'Citizen Request Processing Report',
    storage: 's3://reports/citizen-requests/',
  },
};

export const PROCESS_CLINICAL_TRIAL_DATA_TEAM_SPEC_0_0_1: TeamSpec = {
  id: 'process-clinical-trial-data',
  version: '0.0.1',
  name: 'Process Clinical Trial Data',
  description: `A multi-agent team that automates clinical trial data processing across dozens of trial sites. Harmonises patient records and lab results to CDISC SDTM format, detects safety signals and adverse events in real time, and prepares submission-ready datasets — all with strict HIPAA and GxP compliance guardrails.`,
  tags: [
    'healthcare',
    'pharma',
    'clinical-trials',
    'patient-data',
    'compliance',
  ],
  enabled: true,
  icon: 'heart',
  emoji: '🏥',
  color: '#cf222e',
  agentSpecId: 'process-clinical-trial-data:0.0.1',
  orchestrationProtocol: 'datalayer',
  executionMode: 'sequential',
  supervisor: {
    name: 'Clinical Data Orchestrator Agent',
    model: 'anthropic-claude-sonnet-4',
  },
  routingInstructions: `Route incoming data through the Ingestion Agent first for format detection and parsing, then to Harmonisation Agent for CDISC SDTM standardisation, then Safety Monitor for adverse event screening, then Submission Preparer for final dataset assembly. Escalate serious adverse events (SAEs) immediately to the medical officer.`,
  validation: { timeout: '600s', retryOnFailure: true, maxRetries: 2 },
  agents: [
    {
      id: 'ct-1',
      name: 'Data Ingestion Agent',
      role: 'Primary · Initiator',
      goal: `Ingest patient records, lab results, and CRFs from clinical sites`,
      model: 'openai-gpt-4-1',
      mcpServer: 'Clinical EDC MCP',
      tools: [
        'Medidata Connector',
        'Veeva Vault Reader',
        'Oracle Clinical Adapter',
        'Format Detector',
      ],
      trigger: 'Event: new data batch received from site',
      approval: 'auto',
    },
    {
      id: 'ct-2',
      name: 'Harmonisation Agent',
      role: 'Secondary',
      goal: `Standardise all data to CDISC SDTM format with MedDRA coding`,
      model: 'openai-gpt-4-1',
      mcpServer: 'Data Standards MCP',
      tools: [
        'SDTM Mapper',
        'MedDRA Coder',
        'Unit Converter',
        'Site Normaliser',
      ],
      trigger: 'On completion of Data Ingestion Agent',
      approval: 'auto',
    },
    {
      id: 'ct-3',
      name: 'Safety Monitor Agent',
      role: 'Secondary',
      goal: `Screen every data point for adverse events and safety signals`,
      model: 'anthropic-claude-sonnet-4',
      mcpServer: 'Safety Database MCP',
      tools: [
        'AE Classifier',
        'Signal Detector',
        'SAE Escalator',
        'Evidence Trail Builder',
      ],
      trigger: 'On completion of Harmonisation Agent',
      approval: 'manual',
    },
    {
      id: 'ct-4',
      name: 'Submission Preparer Agent',
      role: 'Final',
      goal: `Assemble submission-ready SDTM datasets with validation and define.xml`,
      model: 'openai-gpt-4-1',
      mcpServer: 'Submission MCP',
      tools: [
        'Dataset Validator',
        'Define.xml Generator',
        'PDF Report Builder',
        'Compliance Checker',
      ],
      trigger: 'On completion of Safety Monitor Agent',
      approval: 'auto',
    },
  ],
  reactionRules: [
    {
      id: 'rr-clin-1',
      trigger: 'safety_signal_detected',
      action: 'halt_and_escalate',
      auto: true,
      maxRetries: 0,
      escalateAfterRetries: 0,
      priority: 'critical',
    },
    {
      id: 'rr-clin-2',
      trigger: 'data_integrity_violation',
      action: 'quarantine_and_notify',
      auto: true,
      maxRetries: 1,
      escalateAfterRetries: 1,
      priority: 'critical',
    },
  ],
  healthMonitoring: {
    heartbeatInterval: '10s',
    staleThreshold: '45s',
    unresponsiveThreshold: '90s',
    stuckThreshold: '180s',
    maxRestartAttempts: 2,
  },
  notifications: {
    on_start: true,
    on_completion: true,
    on_failure: true,
    on_escalation: true,
  },
  output: {
    formats: ['pdf', 'json', 'xml'],
    template: 'Clinical Trial Data Report',
    storage: 's3://reports/clinical-trials/',
  },
};

export const SYNC_CRM_CONTACTS_TEAM_SPEC_0_0_1: TeamSpec = {
  id: 'sync-crm-contacts',
  version: '0.0.1',
  name: 'Sync CRM Contacts',
  description: `A multi-agent team that collects and aggregates contact data from multiple CRM sources, analyzes and deduplicates records, writes cleaned data back, and generates sync summary reports.`,
  tags: ['sales', 'crm', 'data-sync', 'deduplication'],
  enabled: true,
  icon: 'people',
  emoji: '🔄',
  color: '#0969da',
  agentSpecId: 'sync-crm-contacts:0.0.1',
  orchestrationProtocol: 'datalayer',
  executionMode: 'sequential',
  supervisor: {
    name: 'CRM Orchestrator Agent',
    model: 'anthropic-claude-opus-4',
  },
  routingInstructions: `Route data collection tasks to the Data Collector first, then analysis, then sync, then reporting. Escalate to human if sync fails 3 times.`,
  validation: { timeout: '300s', retryOnFailure: true, maxRetries: 3 },
  agents: [
    {
      id: 'tm-1',
      name: 'Data Collector Agent',
      role: 'Primary · Initiator',
      goal: `Collect and aggregate contact data from multiple CRM sources`,
      model: 'openai-gpt-4-1',
      mcpServer: 'Data Processing MCP',
      tools: ['API Connector', 'Data Parser'],
      trigger: 'Schedule: Daily at 2:00 AM',
      approval: 'auto',
    },
    {
      id: 'tm-2',
      name: 'Analyzer Agent',
      role: 'Secondary',
      goal: `Analyze collected data and identify patterns and duplicates`,
      model: 'anthropic-claude-opus-4',
      mcpServer: 'Analytics MCP',
      tools: ['Statistical Analysis', 'ML Predictor', 'Deduplicator'],
      trigger: 'On completion of Data Collector',
      approval: 'manual',
    },
    {
      id: 'tm-3',
      name: 'Sync Writer Agent',
      role: 'Secondary',
      goal: `Write cleaned and merged contacts back to the CRM systems`,
      model: 'openai-gpt-4-1',
      mcpServer: 'CRM Write MCP',
      tools: ['Salesforce Connector', 'HubSpot Connector'],
      trigger: 'On completion of Analyzer',
      approval: 'manual',
    },
    {
      id: 'tm-4',
      name: 'Report Generator Agent',
      role: 'Final',
      goal: `Generate sync summary reports and send notifications`,
      model: 'openai-gpt-4-1',
      mcpServer: 'Document Generation MCP',
      tools: ['PDF Generator', 'Chart Builder', 'Email Sender'],
      trigger: 'On completion of Sync Writer',
      approval: 'auto',
    },
  ],
  reactionRules: [
    {
      id: 'rr-crm-1',
      trigger: 'sync_conflict_detected',
      action: 'log_and_skip',
      auto: true,
      maxRetries: 3,
      escalateAfterRetries: 3,
      priority: 'medium',
    },
    {
      id: 'rr-crm-2',
      trigger: 'api_rate_limit_hit',
      action: 'backoff_and_retry',
      auto: true,
      maxRetries: 5,
      escalateAfterRetries: 5,
      priority: 'low',
    },
  ],
  healthMonitoring: {
    heartbeatInterval: '30s',
    staleThreshold: '120s',
    unresponsiveThreshold: '300s',
    stuckThreshold: '600s',
    maxRestartAttempts: 3,
  },
  notifications: {
    on_start: false,
    on_completion: true,
    on_failure: true,
    on_escalation: false,
  },
  output: {
    formats: ['json', 'csv'],
    template: 'CRM Sync Summary',
    storage: 's3://reports/crm-sync/',
  },
};

// ============================================================================
// Team Specs Registry
// ============================================================================

export const TEAM_SPECS: Record<string, TeamSpec> = {
  'analyze-campaign-performance': ANALYZE_CAMPAIGN_PERFORMANCE_TEAM_SPEC_0_0_1,
  'analyze-support-tickets': ANALYZE_SUPPORT_TICKETS_TEAM_SPEC_0_0_1,
  'audit-inventory-levels': AUDIT_INVENTORY_LEVELS_TEAM_SPEC_0_0_1,
  'automate-regulatory-reporting':
    AUTOMATE_REGULATORY_REPORTING_TEAM_SPEC_0_0_1,
  'comprehensive-sales-analytics':
    COMPREHENSIVE_SALES_ANALYTICS_TEAM_SPEC_0_0_1,
  'optimize-grid-operations': OPTIMIZE_GRID_OPERATIONS_TEAM_SPEC_0_0_1,
  'process-citizen-requests': PROCESS_CITIZEN_REQUESTS_TEAM_SPEC_0_0_1,
  'process-clinical-trial-data': PROCESS_CLINICAL_TRIAL_DATA_TEAM_SPEC_0_0_1,
  'sync-crm-contacts': SYNC_CRM_CONTACTS_TEAM_SPEC_0_0_1,
};

function resolveTeamId(teamId: string): string {
  if (teamId in TEAM_SPECS) return teamId;
  const idx = teamId.lastIndexOf(':');
  if (idx > 0) {
    const base = teamId.slice(0, idx);
    if (base in TEAM_SPECS) return base;
  }
  return teamId;
}

/**
 * Get a team specification by ID.
 */
export function getTeamSpec(teamId: string): TeamSpec | undefined {
  return TEAM_SPECS[resolveTeamId(teamId)];
}

/**
 * List all available team specifications.
 *
 * @param prefix - If provided, only return specs whose ID starts with this prefix.
 */
export function listTeamSpecs(prefix?: string): TeamSpec[] {
  const specs = Object.values(TEAM_SPECS);
  return prefix !== undefined
    ? specs.filter(s => s.id.startsWith(prefix))
    : specs;
}
