# Copyright (c) 2025-2026 Datalayer, Inc.
# Distributed under the terms of the Modified BSD License.

"""
PDF output generator using the Jupyter sandbox.

Converts agent Markdown output → HTML (via Jinja2 template) → PDF (via
WeasyPrint executed in the Jupyter sandbox kernel). The generated PDF
is stored locally and can be uploaded to S3 user space.
"""

from __future__ import annotations

import logging
import os
import tempfile

import httpx

from .base import AgentResult, BaseOutputGenerator, OutputArtifact

logger = logging.getLogger(__name__)

_DEFAULT_OUTPUT_DIR = os.path.join(tempfile.gettempdir(), "agent-output")

# Default template: just wrap markdown-rendered HTML in a basic page
_DEFAULT_HTML_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body { font-family: 'Helvetica Neue', Arial, sans-serif; margin: 40px; line-height: 1.6; }
    h1, h2, h3 { color: #1f2328; }
    table { border-collapse: collapse; width: 100%; margin: 16px 0; }
    th, td { border: 1px solid #d1d9e0; padding: 8px 12px; text-align: left; }
    th { background: #f6f8fa; font-weight: 600; }
    pre { background: #f6f8fa; padding: 16px; border-radius: 6px; overflow-x: auto; }
    code { font-family: 'SFMono-Regular', Consolas, monospace; font-size: 0.9em; }
    .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #d1d9e0;
              color: #656d76; font-size: 0.85em; }
  </style>
</head>
<body>
{{ content }}
<div class="footer">
  Generated by Datalayer Agent &middot; {{ timestamp }}
</div>
</body>
</html>
"""


class PDFOutputGenerator(BaseOutputGenerator):
    """Generate PDF output from agent results using the Jupyter sandbox.

    The generation pipeline:
    1. Agent produces structured Markdown.
    2. Render Markdown → HTML using Jinja2 template.
    3. Execute HTML → PDF conversion via WeasyPrint in the Jupyter sandbox.
    4. Return the local file path (caller can upload to S3).

    Parameters
    ----------
    template_path : str | None
        Path to a Jinja2 HTML template. If None, uses built-in default.
    sandbox_url : str
        URL of the Jupyter sandbox kernel gateway.
    output_dir : str
        Directory for storing generated PDFs.
    """

    def __init__(
        self,
        template_path: str | None = None,
        sandbox_url: str = "http://localhost:8888",
        output_dir: str = _DEFAULT_OUTPUT_DIR,
    ):
        self.template_path = template_path
        self.sandbox_url = sandbox_url
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)

    async def generate(self, agent_result: AgentResult) -> OutputArtifact:
        """Convert agent output to PDF via the Jupyter sandbox."""

        # 1. Render HTML from agent output
        html_content = self._render_html(agent_result)

        # 2. Generate PDF via sandbox or local fallback
        pdf_path = await self._generate_pdf(html_content, agent_result.agent_id)

        # 3. Build artifact
        size = os.path.getsize(pdf_path) if os.path.exists(pdf_path) else 0
        filename = f"{agent_result.agent_id}_output.pdf"

        artifact = OutputArtifact(
            type="pdf",
            url=pdf_path,
            filename=filename,
            size_bytes=size,
            content_type="application/pdf",
            metadata={
                "agent_id": agent_result.agent_id,
                "template": self.template_path or "default",
            },
        )

        logger.info("Generated PDF output: %s (%d bytes)", pdf_path, size)
        return artifact

    def _render_html(self, agent_result: AgentResult) -> str:
        """Render agent output as HTML using Jinja2."""
        try:
            from jinja2 import Template
        except ImportError:
            logger.warning("jinja2 not available, using plain HTML wrapper")
            return f"<html><body><pre>{agent_result.final_output}</pre></body></html>"

        # Load custom template or use default
        if self.template_path and os.path.exists(self.template_path):
            with open(self.template_path) as f:
                template_str = f.read()
        else:
            template_str = _DEFAULT_HTML_TEMPLATE

        template = Template(template_str)
        from datetime import datetime, timezone

        return template.render(
            content=self._markdown_to_html(agent_result.final_output),
            data=agent_result.structured_data,
            charts=agent_result.charts,
            metadata=agent_result.metadata,
            agent_id=agent_result.agent_id,
            timestamp=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        )

    def _markdown_to_html(self, markdown_text: str) -> str:
        """Best-effort Markdown → HTML conversion."""
        try:
            import markdown  # type: ignore[import-untyped]

            return markdown.markdown(
                markdown_text,
                extensions=["tables", "fenced_code", "codehilite"],
            )
        except ImportError:
            # Minimal fallback: wrap in <pre>
            return f"<pre>{markdown_text}</pre>"

    async def _generate_pdf(self, html_content: str, agent_id: str) -> str:
        """Generate PDF from HTML content.

        Tries the Jupyter sandbox first; falls back to local WeasyPrint.
        """
        pdf_path = os.path.join(self.output_dir, f"{agent_id}_output.pdf")

        # Try sandbox execution
        try:
            return await self._generate_via_sandbox(html_content, pdf_path)
        except Exception as e:
            logger.warning("Sandbox PDF generation failed, trying local: %s", e)

        # Local fallback
        return self._generate_local(html_content, pdf_path)

    async def _generate_via_sandbox(self, html_content: str, pdf_path: str) -> str:
        """Execute WeasyPrint in the Jupyter sandbox kernel."""
        # Write HTML to temp file accessible by sandbox
        html_path = pdf_path.replace(".pdf", ".html")
        with open(html_path, "w") as f:
            f.write(html_content)

        # Build code cells for sandbox execution
        code = f"""
import weasyprint
weasyprint.HTML(filename='{html_path}').write_pdf('{pdf_path}')
print('PDF generated successfully')
"""

        async with httpx.AsyncClient(base_url=self.sandbox_url, timeout=60.0) as client:
            # Execute code via Jupyter kernel gateway API
            resp = await client.post(
                "/api/kernels",
                json={"name": "python3"},
            )
            resp.raise_for_status()
            kernel_id = resp.json()["id"]

            try:
                # Execute cell
                resp = await client.post(
                    f"/api/kernels/{kernel_id}/execute",
                    json={"code": code},
                )
                resp.raise_for_status()
            finally:
                # Shutdown kernel
                await client.delete(f"/api/kernels/{kernel_id}")

        if not os.path.exists(pdf_path):
            raise FileNotFoundError(f"Sandbox did not produce {pdf_path}")

        return pdf_path

    def _generate_local(self, html_content: str, pdf_path: str) -> str:
        """Fallback: generate PDF locally using WeasyPrint."""
        try:
            import weasyprint

            weasyprint.HTML(string=html_content).write_pdf(pdf_path)
            return pdf_path
        except ImportError:
            logger.error(
                "WeasyPrint not available. PDF generation requires either "
                "a Jupyter sandbox or local weasyprint installation."
            )
            # Write HTML as fallback
            html_path = pdf_path.replace(".pdf", ".html")
            with open(html_path, "w") as f:
                f.write(html_content)
            return html_path
